### ISSUE TITLE
Consider using higher order function in reverse filter

### ISSUE THREAD

**Issue by wjamro** [wojtek-zajac/learning-angularjs#1]
Code: https://github.com/wojtek-zajac/learning-angularjs/blob/master/app.js#L47
The code above can be written using higher order functions thus avoiding variable reassignments (let out = '')

Learn:
https://eloquentjavascript.net/05_higher_order.html

Proposed solution:
https://repl.it/@WiktorJamro/GratefulWarmNewsaggregator

**Comment by wojtek-zajac** [comment]
Thanks for the example - however, the `.reduce` method is a bit tricky for me. How about the `.reverse` one as in the [d80fd6a](https://github.com/wojtek-zajac/learning-angularjs/commit/d80fd6a883be46c5a005896645811d765d01052e) commit?
