### ISSUE TITLE
Use $resource instead of $http

### ISSUE THREAD

**Issue by wjamro** [wojtek-zajac/learning-angularjs#3]
`$resource` is widely used across SR so familiarity with this module is required.

Code:
https://github.com/wojtek-zajac/learning-angularjs/blob/master/app.js#L36

Learn:
https://stackoverflow.com/questions/13269882/angularjs-resource-restful-example

**Comment by wojtek-zajac** [comment]
Please review https://github.com/wojtek-zajac/learning-angularjs/commit/74f12d14bbe130668b1b06ecd0d3b39c76ebe36b

**Comment by wjamro** [comment]
@wojtek-zajac  Perfect.

One hint: handle `error` properly e.g. show alert 
https://github.com/wojtek-zajac/learning-angularjs/commit/74f12d14bbe130668b1b06ecd0d3b39c76ebe36b#diff-19b81c2421601d61a1c8cd6cc7a27b0eR12
